---
title: "Data"
author: "Ethan Shen"
date: "9/1/2020"
output: html_document
---

```{r}
library(tidyverse)
library(jsonlite)
```


```{r}
league = read_csv("586003-1093265-bundle-archive/match_data_version1.csv")
champions = read_csv("riot_champion.csv") %>%
  select(key, name)
```


```{r}
league_df = league %>%
  mutate(rownum = row_number())

find_list_columns = function(x) {
  col_check = map_dfr(x, 
                      ~ map(., length)) %>%
    map_lgl(~ any(. > 1 | . == 0, na.rm = TRUE)) # check for null list  elements 
  
  list_cols = names(col_check)[col_check] 
  
  fix_list_cols = function(entry, name) {
    if (name %in% list_cols) {
      list(entry)
    } else {
      entry
    }
  }
  
  map_dfr(x,
          function(char) {
            map2(char, names(char), fix_list_cols) %>%
              as_tibble(validate = NULL
              )
          }
  ) 
}
```


```{r}
if (file.exists("participants.RData")) {
  print("The file participants.RData exists.")
  #load(file = "participants.RData")
} else {
  par_list = list()
  for (i in 1:nrow(league_df)){
    pp = league_df$participants[i]
    pp = pp %>% str_replace_all("'",'"') %>%
      str_replace_all('False', '"False"') %>%
      str_replace_all('True', '"True"')
    write(pp, paste0("/Users/ethanshen/Documents/College/Fa20/STA 440/par.json"))
    par_df = find_list_columns(read_json("/Users/ethanshen/Documents/College/Fa20/STA 440/par.json")) %>%
      mutate(rownum = i)
    par_list[[i]] = par_df
  }
  participants_df = do.call(bind_rows, par_list)
  save(participants_df, file = "participants.RData")
}

#
#
#
if (file.exists("summoners.RData")) {
  print("The file summoners.RData exists.")
  #load(file = "summoners.RData")
} else {
  par_id_list = list()
  for (i in 1:nrow(league_df)){
    pp_id = league_df$participantIdentities[i]
    pp_id = pp_id %>% str_replace_all("'",'"') #%>% str_replace_all('False', '"False"') # %>% str_replace_all('True', '"True"')
    write(pp_id, paste0("/Users/ethanshen/Documents/College/Fa20/STA 440/par_id.json"))
    par_id_df = find_list_columns(read_json("/Users/ethanshen/Documents/College/Fa20/STA 440/par_id.json")) %>%
      mutate(rownum = i)
    par_id_list[[i]] = par_id_df
  }
  par_id_df = do.call(bind_rows, par_id_list)
  player_df = find_list_columns(par_id_df$player)
  player_info = bind_cols(par_id_df %>% select(-player),
                          player_df %>% select(summonerName, summonerId))
  
  save(player_info, file = "summoners.RData")
  
  league_df_w_participants = right_join(league_df %>% 
                                          select(-participants, -participantIdentities), 
                                        inner_join(
                                          participants_df, 
                                          player_info, 
                                          by = c("participantId", "rownum")
                                        ))
}
#
#
#
#

if (file.exists("timeline.Rdata")) {
  print("The file timeline.Rdata exists.")
  #load(file = "timeline.Rdata")
} else {
  timeline = find_list_columns(league_df_w_participants$timeline)
  save(timeline, file = "timeline.Rdata")
  
  league_df_w_participants <- league_df_w_participants %>% 
    bind_cols(timeline) %>% 
    group_by(rownum, win) %>% 
    filter(sum(lane=="JUNGLE") == 1 & sum(lane=="MIDDLE") == 1 & sum(lane=="TOP") == 1 & sum(lane=="BOTTOM") == 2)
}
#
#
#
#

if (file.exists("timeline_per_min.Rdata")) {
  print("The file timeline.Rdata exists.")
  #load(file = "timeline_per_min.Rdata")
} else {
  timeline_list_cols = colnames(league_df_w_participants)[sapply(league_df_w_participants, typeof) == 'list' & str_detect(colnames(league_df_w_participants), "Deltas")]
  
  tl_list = list()
  indexes <- c(1:nrow(league_df_w_participants))
  for (i in 1:length(timeline_list_cols)) {
    col = timeline_list_cols[i]
    tl = league_df_w_participants[[col]] 
    # adding index to each element 
    tl_indexed = mapply(append, tl, indexes, SIMPLIFY = FALSE) 
    
    # assigning a name to the index element, def easier way to do this 
    for (j in 1:nrow(league_df_w_participants)) {
      names(tl_indexed[[j]])[length(tl_indexed[[j]])] <- "index"
    }
    
    tl_df = find_list_columns(tl_indexed)
    colnames(tl_df) = paste(col, colnames(tl_df))
    tl_list[[i]] = tl_df
  }
  
  timeline_per_min = do.call(bind_cols, tl_list) 
  
  timeline_index_cols = colnames(timeline_per_min)[str_detect(colnames(timeline_per_min), "index")]
  
  timeline_per_min = timeline_per_min %>% 
    select(-all_of(timeline_index_cols))
  save(timeline_per_min, file = "timeline_per_min.Rdata")
}

if (file.exists("stats.Rdata")) {
  print("The file stats.Rdata exists.")
  #load(file = "summoners.RData")
} else {
  stats = find_list_columns(league_df_w_participants$stats)
  save(stats, file = "stats.Rdata")
}

if (file.exists("league_df_final.Rdata")) {
  load(file = "league_df_final.Rdata")
} else {
  league_df_final = bind_cols(league_df_w_participants %>% 
                                select(-stats, -timeline, -all_of(timeline_list_cols)),
                              stats,
                              timeline_per_min) %>% 
    select(-(combatPlayerScore:statPerk2))
  
  save(league_df_final, file = "league_df_final.Rdata")
}
```

```{r}
champions <- read_csv("data/riot_champion.csv") %>% select(name, key)

league_df_final <- league_df_final %>% 
  left_join(champions, by = c("championId" = "key"))

# these are games where the botlane is recorded as duo, instead of duo_carry vs duo_support
# filter these out
duo_games <- league_df_final %>% 
  filter(role == "DUO") %>% pull(rownum) %>% unique()

league_df_final <- league_df_final %>% 
  filter(! rownum %in% duo_games) 

league_df_final <- league_df_final %>% 
  mutate(role = case_when(
    role == "DUO_SUPPORT" & lane == "BOTTOM" ~ "SUPPORT",
    TRUE ~ lane)) %>% 
  mutate(role = str_to_title(role),
         role = factor(role, levels = c("Top", "Jungle", "Middle", "Bottom", "Support")))


primary_role_df <- league_df_final %>% 
  group_by(name, role) %>% 
  summarise(n = n()) %>% 
  arrange(name, desc(n)) %>% 
  group_by(name) %>% 
  top_n(1, wt = n) %>% 
  mutate(primary_role = role)

league_df_final <- league_df_final %>%  
  left_join(primary_role_df %>% select(primary_role), 
            by = c("name")) %>% 
  ungroup() %>% 
  mutate(off_role = case_when(
    role == primary_role ~ 1,  
    role != primary_role ~ 0
  ))

save(league_df_final, file = "data/league_df_final.Rdata")
```


```{r champ-class, include=FALSE}
url <- "https://leagueoflegends.fandom.com/wiki/List_of_champions"

read_html(url) %>% 
  html_nodes('table') %>% 
  .[2] %>% 
  html_table() %>% 
  as.data.frame() %>% 
  separate(col = Champion, into = c("name", "description"), sep = ",") %>% 
  separate(col = name, into = c("name", "description"), sep = "the") %>% 
  mutate(champ_class = Primary,
         name = str_trim(name),
         name = case_when(
           name == "Pan" ~ "Pantheon",
           TRUE ~ as.character(name)
         )) %>% 
  select(name,champ_class) %>% saveRDS("data/champ_class_df.Rds")
```

```{r champ-mastery, include=FALSE}
bind_rows(readRDS("data/champ_mastery/champ_mastery.Rds"), #1-20000
          readRDS("data/champ_mastery/champ_mastery2.Rds"), #20001-30000
          readRDS("data/champ_mastery/champ_mastery3.Rds") #30001 onward
) %>% 
  group_by(summonerName, championId) %>% 
  distinct() %>% 
  arrange(desc(championPoints)) %>% 
  top_n(1, championPoints) %>% 
  ungroup() %>% saveRDS("data/final_champ_mastery.Rds")
```

```{r combining-data, include=FALSE}
load("data/league_df_final.Rdata")
readRDS("data/final_champ_mastery.Rds") %>% 
  right_join(league_df_final %>% select(-summonerId),
             by = c("summonerName",  "championId")) %>% 
  arrange(rownum) %>% 
  distinct() %>%  
  left_join(readRDS("data/champ_class_df.Rds") %>% 
              mutate(main_class = case_when(
                champ_class %in% c("Enchanter", "Catcher") ~ "Controller",
                champ_class %in% c("Juggernaut",  "Diver") ~ "Fighter",
                champ_class %in% c("Burst",  "Battlemage", "Artillery") ~ "Mage",
                champ_class %in% c("Assassin",  "Skirmisher") ~ "Slayer",
                champ_class %in% c("Vanguard",  "Warden") ~ "Tank",
                champ_class == "Marksman" ~ "Marksman",
                champ_class == "Specialist" ~ "Specialist")
              ), by = "name") %>% 
  ungroup() %>% 
  distinct() %>% 
  group_by(rownum, teamId)  %>% 
  mutate(team_comp = paste(sort(main_class), collapse = ", ")) %>% 
  mutate(offensive = case_when(
    main_class %in% c("Mage","Marksman","Fighter", "Slayer") ~ 1,
    main_class == "Specialist" ~ 0.5,
    main_class %in% c("Tank", "Controller") ~ 0
  )) %>% 
 
  mutate(team_comp_offensive = ifelse(sum(offensive) > 2.5, 1, 0))%>% 
  left_join(readRDS("totalchampionmasteryscore.Rds"), 
            by = "summonerId") %>% 
  
  saveRDS("final_data.Rds")
```
